config/routes.rb
Hoo::Application.routes.draw do
  



  get "connection/index", as: :connections
  

  resources :platforms


  get "beta/index"

  get "beta/work"

  get "beta/user"
  
  get "beta/add_credit"
  
  get "front/stats"

  resources :emails


  get "front/index"
  get "front/validate_email_credit"
  get "front/validate_new_email_credit"
  resources :betausers
  
  resources :betasessions
  
  resources :friendships
  resources :messages

  resources :posts


  resources :product_genres


  resources :credit_validations do
    member do
      put :validate
      put :flag
      put :validation
    end
  end


  resources :credits do
    collection do
      get :recent
      post :import 
      match 'role'
      match 'search'
      match 'batch'
      put :claim
    end
    member do
      put :increase
      put :flag
      put :claim
    end
  end


  resources :products, execpt: [:index, :destroy] do

    member do
      post :invite
    end

    collection do
      get :recent
      get :popular
    end
    #member do
    #get 'like'
    #get 'complete'
    #end
  end


#Rails Admin
mount RailsAdmin::Engine => '/lecrabe', :as => 'rails_admin'


#Session Routes
get "sessions/new"


#User Routes
resources :users
match 'auth/:provider/callback', to: 'sessions#create'
match 'auth/failure', to: redirect('/')
match 'signout', to: 'sessions#destroy', as: 'signout'
match 'users', to: 'users#index', as: 'users'


#Products
match '/rate' => 'rater#create', :as => 'rate'

#Search

match "search", to: 'search#index', :as => 'search'

#Temp 
get "holding/index"

match "message_preview", to: 'credits#validate-message', :as => 'message_preview'
#Front

match "legal", to: 'front#legal', :as => 'legal'
get :terms, to: "front#terms"
get :privacy, to: "front#privacy"
match "suggested", to: 'front#suggested', :as => 'suggested'

root :to => "beta#index"

 
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  def index
    @credits = Credit.limit(10).order("created_at DESC")
       @users_featured = User.find_all_by_id([13, 19, 3, 12])
         @most_user_credits = User.limit(4).order("credits_count DESC")
            @most_product_credits = Product.limit(4).order("credits_count DESC")
     if current_user
        @credit_validations = CreditValidation.where(:validator_id => current_user.id).where(:status => "pending")
        @emails = Email.where(:user_id => current_user.id)
        @emails.each do |email|
          @unclamied_email_credits = Credit.where(:pending_user_email => email.email)
            end
            
            @related_credits = Credit.where(:user_id => current_user.id)
              @related_credits.each do |rc|
              @studio = rc.product.studio
                @products = Product.where(:studio => @studio)
                @products.each do |p|
                  @related_products = Product.where(:studio => @studio)
                end
            end  
                  
                
          @unclaimed = Credit.where(:status => "pending").where(:pending_user_email => current_user.email).where(:user_id => nil)
            @flagged_credits = CreditValidation.where(:user_id => current_user.id).where(:status => "pending").where(:credit_id => true)  
              @empty_credits = Credit.where(:user_id => current_user.id).limit(3)
        @credit_validation = CreditValidation.new
         @credit = Credit.new
     end
   end

def validate_new_email_credit
  @credit = Credit.find_by_id(params[:credit_id])
  @credit.pending_user_email = current_user.email
  @credit.confirmed_validations_count = @credit.credit_validations.confirmed.count
  @credit.user_id = current_user.id
  @credit.status = "confirmed"
  if @credit.save
    redirect_to root_url
  end
end   


def stats
  if current_user.googleplus == "lecrabe"
    @users = User.order(:updated_at)
    @cv = CreditValidation.all
  @users_total = User.all.size
  @users_with_credits = User.where("credits_count > ?", 0).size
  @users_with_credits_percentage = @users_with_credits * 100 / @users_total
  @users_last_day = User.where("created_at > ?", 24.hours.ago).size
  @users_last_week = User.where("created_at > ?", 1.week.ago).size
  @users_last_month = User.where("created_at > ?", 1.month.ago).size
  
  @users_with_facebook = User.where(:provider => "facebook").size
  @users_with_facebook_percentage = @users_with_facebook * 100 / @users_total
  @users_with_bio = User.where(:bio => nil).size
  @users_with_bio_percentage = @users_with_bio - @users_total * 100 / @users_total

  
  @credits_total = Credit.all.size
  @credits_with_verifiers = Credit.where("credit_validation_count > ?", 0).size
  @credits_with_verifiers_percentage = @credits_with_verifiers * 100 / @credits_total  
  @credits_last_day = Credit.where("created_at > ?", 24.hours.ago).size
  @credits_last_week = Credit.where("created_at > ?", 1.week.ago).size
  @credits_last_month = Credit.where("created_at > ?", 1.month.ago).size

  
  @cv_total = CreditValidation.all.size
  @cv_confirmed = CreditValidation.where(:status => "confirmed").size
  @cv_percentage = @cv_confirmed * 100 / @cv_total
  @credits_v_last_day = CreditValidation.where("created_at > ?", 24.hours.ago).size
  @credits_v_last_week = CreditValidation.where("created_at > ?", 1.week.ago).size
  @credits_v_last_month = CreditValidation.where("created_at > ?", 1.month.ago).size
else
  redirect_to root_url
end
end 

def suggested
  @product = Product.find_by_id(params[:product_id])
  @suggested = Product.where(:studio => @product.studio).limit(4)
  if @suggested.empty?
    redirect_to product_path(@product)
  end
end
  
end

app/helpers/front_helper.rb
module FrontHelper
end

app/views/front/index.html 2.erb
<div class="container_12 index-header">
	<div class="grid_6 alpha">
		<h1>Welcome to whoactually
			<% if current_user %>
			<% else %>
			Thank you for taking part.</h1>
			<% end %>
	</div>

		<div class="grid_6 push_1 search omega">
			<%= form_tag search_credits_path, :method => 'get' do %>

			  <%= text_field_tag :search, params[:search], data: {autocomplete_source: Product.order(:title).map(&:title)} %>
			     <%= submit_tag "SEARCH", :name => nil, :class => "search-button" %>
			  <%end%>
		
		</div>
</div>


	<div class="white-box">
	
		
<% if current_user %>
<p>The platform for all Creators to own and manage their Credits and get the public recognition they deserve.</p>

<% else %>
<p>We use facebook as the first level of validation to prove you're identity so that you can begin to claim the creative credits on media products (games, film, comics, web) you feel you deserve and find colleagues to validate those claims.</p>

<p>We will NOT POST ANYTHING TO YOUR WALL or contact any of your friends. The facebook login is purely to validate that you are who you say you are. We will only use your profile picture and your registered email address to communicate with you ONLY. We hate spam as much as you do.</p>

		<p>Please  <%= link_to "register/login via Facebook.", "/auth/facebook", id: "login_with_facebook"  %> 
 	<% end %>
	</div>


<div class="product-list">
	<h2>Featured Members</h2>
		<ul class="product-list">
			<% @users_featured.each do |u| %>
		<%= link_to u do %>
<li class="product-list">
<span style="margin-left:40px;"><img src="http://graph.facebook.com/<%= u.uid%>/picture?type=small"></span>
<h3> <%= u.name %></h3>

</li>
<%end%><%end%>	
		</ul>
</div>

<% if current_user %>

<div class="container_12 credits-form">
	<% if @unclaimed.empty?%>
	<% else %>
	<h1>Unclaimed Credits</h1>
		<div class= "activity-feed">
			<ul>
	<% @unclaimed.each do |u| %>
		<li class="<%= cycle('even', 'odd') -%>"><h3><%= u.role %> <%= u.user_id %>on <%= u.product.title %></h3> <span class="right" style="margin-top:-80px;"><%= link_to "Claim Credit", front_validate_email_credit_url(:credit_id => u.id), :class => "blue-link" %> </span> </li>
	<%end%>	
	<% end %>
	</ul>
	</div>
	
	
	<% if @unclamied_email_credits  %>
	
	<% else %>
	<h1>Unclaimed Credits matching other email addresses</h1>
	<div class= "activity-feed">
		<ul>
	<% @unclamied_email_credits.each do |u| %>
		<li class="<%= cycle('even', 'odd') -%>"><h3><%= u.role %> <%= u.user_id %>on <%= u.product.title %></h3> <span class="right" style="margin-top:-80px;"><%= link_to "Claim Credit", front_validate_new_email_credit_url(:credit_id => u.id), :class => "blue-link" %> </span> </li>
	<% end %>
	<% end %>
</ul> 	

	</div>
</div>



<div class="container_12 credits-form">
	
	<% if @empty_credits.empty? %>
	<% else %>
	<h1>Your Credits</h1>
	<% end %>
<ul>
	<% @empty_credits.each do |c| %>
	
	<li class="<%= cycle('even', 'odd') -%>">
		
		
	<h2><% if c.product.image? %>
			<%= image_tag c.product.image.thumb.to_s %>
				 <%else%> 
			<%= image_tag '/assets/default-credit-small.jpg'%>
	 <%end%>  
	   
	 
	 
	  <%= c.role%><% if current_user %>			
<% if current_user.id == c.user_id %> <%= link_to "(edit)", role_credits_path(:id => c) %> <% end %> <% end %> on   <%= link_to c.product.title, product_path(c.product)%></h2>
	
	
	<%= render '/credits/ticks', :c => c %>		

<br /><br /><br /><br />
	   
				
	<%= render '/credits/more-detail', :c => c %>	

	

<div class="container_12">

<%= link_to 'Delete', c, method: :delete, data: { confirm: 'Are you sure?' }, :class => "blue-link" %>
</div>


	<%= render '/credits/validate-credit', :c => c, :p => c.product %>	


<%end%>

	</li>
			
</ul>
</div>



<% if @credit_validations.empty? %>
<% else %>
<h1>Validation Requests</h1>
<% end %>

<div class="container_12 credits-form">
	<ul>
	<% @credit_validations.each do |cv| %>
		<% c = Credit.find_by_id(cv.credit_id)%>
		<li class="<%= cycle('even', 'odd') -%>">
		<h2><% if c.product.image? %>
				<%= image_tag c.product.image.thumb.to_s %>
					 <%else%> 
				<%= image_tag '/assets/default-credit-small.jpg'%>
		 <%end%>  
	
  <%= c.user.name %> was a <%= c.role%>  on   <%= link_to c.product.title, product_path(c.product)%></h2>
   		
				
   		<% if cv.status == "confirmed" %>
   		<span class="score">
   		<a href="/users/<%= cv.validator_id %>"><img src="http://graph.facebook.com/<%= @user.uid%>/picture?type=square" style="margin-top:-5px;"></a>
   		</span>
   		<% end %>
   			<% if cv.status == "pending" %>
   		<span class="score">
   		<a href="/credit_validations/<%= cv.id %>"><%= image_tag '/assets/pending.png' %></a>
					
   				<% if current_user %>
   					<% if current_user.id == cv.validator_id %>
							
   					<%= link_to "Validate", validate_credit_validation_path(cv), :method=>:put  %>
   				<% end %>
   			<% end %>
   		<% end %>
   		</span>
   	
   <br /><br /><br /><br />
		<div class="more-detail">		
		<h3>'What I actually did: <% if current_user %>			
<% if current_user.id == c.user_id %> <%= link_to "(edit)", role_credits_path(:id => c) %> <% end %> <% end %> </h3><p>  <%= c.role_desc %></p>	
			<h3>Insider Stories: <% if current_user %>			
<% if current_user.id == c.user_id %>(click below to edit) <% end %> <% end %>
</h3><p><%= best_in_place c, :fact, :type => :textarea, :nil => "Click me to add content!", :ok_button => 'Save', :cancel_button => 'Cancel' %></p>
		</div>
  
		</li>
	<% end %>
	</ul>

</div>
<% if @flagged_credits.empty? %>
<% else %>
<h2>Your Pending Credits:</h2>
<% end %>
<div class="container_12 credits-form">
	<ul>
	<% @flagged_credits.each do |cv| %>
		<% c = Credit.find_by_id(cv.credit_id)%>
		<li class="<%= cycle('even', 'odd') -%>">
		<h2><% if c.product.image? %>
				<%= image_tag c.product.image.thumb.to_s %>
					 <%else%> 
				<%= image_tag '/assets/default-credit-small.jpg'%>
		 <%end%>  
	
  <%= c.user.name %> was a <%= c.role%>  on   <%= link_to c.product.title, product_path(c.product)%></h2>
   		
				
   		<% if cv.status == "confirmed" %>
   		<span class="score">
   		<a href="/users/<%= cv.validator_id %>"><img src="http://graph.facebook.com/<%= @user.uid%>/picture?type=square" style="margin-top:-5px;"></a>
   		</span>
   		<% end %>
   			<% if cv.status == "pending" %>
   		<span class="score">
   		<a href="/credit_validations/<%= cv.id %>"><%= image_tag '/assets/pending.png' %></a>
					
   				<% if current_user %>
   					<% if current_user.id == cv.validator_id %>
							
   					<%= link_to "Validate", validate_credit_validation_path(cv), :method=>:put  %>
   				<% end %>
   			<% end %>
   		<% end %>
   		</span>
   	
   <br /><br /><br /><br />
		<div class="more-detail">		
		<h3>Role description: <% if current_user %>			
<% if current_user.id == c.user_id %> <%= link_to "(edit)", role_credits_path(:id => c) %> <% end %> <% end %> </h3><p>  <%= c.role_desc %></p>	
			<h3>Insider Stories: <% if current_user %>			
<% if current_user.id == c.user_id %>(click below to edit) <% end %> <% end %>
</h3><p><%= best_in_place c, :fact, :type => :textarea, :nil => "Click me to add content!", :ok_button => 'Save', :cancel_button => 'Cancel' %></p>
		</div>
		
		</li>
	<% end %>
	</ul>

</div>

<% end %>




<div class="container_12 activity-feed">
	<h2>New Credits</h2>
		<ul>
			<% @credits.each do |c| %>
			<% if c.user %>
			<li class="<%= cycle('even', 'odd') -%>"><span class="timesince"><%= time_ago_in_words(c.created_at) %></span><img src="http://graph.facebook.com/<%= c.user.uid%>/picture?type=square" style="margin:5px;"> <%= link_to c.user.name, user_path(c.user) %> -   <%= link_to c.product.title, product_path(c.product)%>  <span class="right">Credit Added</span></li>
			<%else%>
			<%end%>
			<%end%>	
		</ul>
</div>

app/views/front/index.html.erb
<% @cr = Credit.all %>
<% @cr.each do |cr| %>
<% @cv = CreditValidation.where(:credit_id => cr.id).where(:status => "confirmed" ) %>
<%= cr.id %>
<%= @cv.count %><br />
<% end %>

app/views/front/index.js.erb
$('#comments').append('<%= j render(@comments) %>');
CommentPoller.poll();

app/views/front/legal.html.erb
<div class="search_header">
<div class="container_12">
  <h1 class="gird_12">Legal</h1>
</div>
</div>

<div class="container_12">
  <div class="grid_12">
  </div>
</div>

app/views/front/privacy.html.erb
<div class="search_header">
<div class="container_12">
  <h1 class="gird_12">Privacy</h1>
</div>
</div>

<div class="container_12">
  <div class="grid_12">
  </div>
</div>

app/views/front/stats.html.erb
<div class="container_12 pages">
	<h1>Stats Users</h1>

	<h1>Listing users</h1>

	<table>
	  <tr>
	    <th>Name</th>
	    <th>Credits Count</th>
		  <th>Credit validations in</th>
	 <th>Credit validations sent</th>
	    <th>Date opend</th>
	    <th>Date of last visit</th>
		<th>Revisted</th>
	  </tr>

	<% @users.each do |u| %>
	<% @cvrec = CreditValidation.where(:user_id => u.id) %>
	<% @cvsent = CreditValidation.where(:validator_id => u.id) %>
	  <tr>
	    <td><%= link_to u.name, users_path(u.id) %></td>
	    <td><%= u.credits.count %></td>
		<td><%= @cvrec.count %></td>
		<td><%= @cvsent.count %></td>
		  <td><%= u.created_at.strftime("%d %m %y") %></td>
	    <td><%= u.updated_at.strftime("%d %m %y") %></td>
		<td><% if u.created_at == u.updated_at %><% else %> Y<% end %></td>
	    <td></td>
	    <td></td>
	    <td></td>
  
	  </tr>
	<% end %>
	</table>

	<br />
	
	<h1>Listing validations</h1>

	<table>
	  <tr>
	    <th>Name</th>
		<th>Credit ID</th>
		<th>Status</th>
		<th>Created at</th>
	  </tr>

	<% @cv.each do |c| %>

	  <tr>
	    <td><%= link_to c.user_id, users_path(c.user_id) %></td>
		<td><%= c.credit_id %>
		<td><%= c.status %></td>
	
		  <td><%= c.created_at.strftime("%d %m %y") %></td>
	  
	  
		
	    <td></td>
	    <td></td>
	    <td></td>
  
	  </tr>
	<% end %>
	</table>

	<br />
	


<h3>Total Number of Users:</h3>	
<h2><%= @users_total %></h2>

<h3>Total Number of Users with at least 1 credit:</h3>
<h2><%= @users_with_credits %></h2>

<h3>Conversion Percentage:</h3>
<h2><%= @users_with_credits_percentage %>%</h2>

<h3>Percentage Registered with Facebook</h3>
<h2><%= @users_with_facebook_percentage %>%</h2>

<h3>New users in the:</h3>
<h2>Last day: <%= @users_last_day %>, Last week: <%= @users_last_week %>, Last month: <%= @users_last_month %></h2>

<h3>Percentage with Bio</h3>
<h2><%= @users_with_bio_percentage %>%</h2>

<h1>Stats Credits</h1>

<h3>Total Number of Credits:</h3>	
<h2><%= @credits_total %></h2>

<h3>Total Number of Credits with at least 1 verifier:</h3>
<h2><%= @credits_with_verifiers %></h2>

<h3>Conversion Percentage:</h3>
<h2><%= @credits_with_verifiers_percentage %>%</h2>

<h3>New Credits in the:</h3>
<h2>Last day: <%= @credits_last_day %>, Last week: <%= @credits_last_week %>, Last month: <%= @credits_last_month %></h2>


<h1>Stats Credit Verifications</h1>
<h3>Total number of Credit Verifications sent out</h3>
<h2><%= @cv_total %></h2>

<h3>Total of confirmed Credit Verifications</h3>
<h2><%= @cv_confirmed %></h2>

<h3>Conversion Percentage:</h3>
<h2><%= @cv_percentage %>%</h2>

<h3>New Credit Verifications in the:</h3>
<h2>Last day: <%= @credits_v_last_day %>, Last week: <%= @credits_v_last_week %>, Last month: <%= @credits_v_last_month %></h2>





</div>

app/views/front/suggested.html.erb
<div class="container_12 pages">
	<div class="grid_12">
		
	
	<h1>Other suggested works:</h1>
	<div class="suggested">
		<ul>
			<% @suggested.each do |p| %>
				<%= link_to product_path(p) do %>
				<li style="min-width:210px; min-height:293px;">
					<% if p.image %>				
					<%= image_tag p.image %><br />
					<% else %>
					<%= image_tag 'assets/beta/logo-with-bg.png' %><br />
					<% end %>
					<h3><%= p.title %></h3><br />
					<p>Add Credit +</p>
		
				</li>
				<% end %>
			<% end %>
		</ul>
		</div>
		
		<div class="grid_12">
		<h2><%= link_to product_path(@product.id) do %>Return to <%= @product.title %><% end %></h2>
		</div>
		</div>
	</div>
</div>
	

app/views/front/terms.html.erb
<div class="search_header">
<div class="container_12">
  <h1 class="grid_12">Terms & Conditions</h1>
</div>
</div>

<div class="container_12">

  <div class="grid_12">


    <p>By using this website you are accepting all the terms of this disclaimer notice.  If you do not agree with anything in this notice you should not use this website.</p>

    <p>Unless otherwise stated, we or our licensors own the intellectual property rights in the website and material on the website.  Subject to the terms below, all these intellectual property rights are reserved.</p>

    <p>The information contained in this website is for general information purposes only. The information is provided by Itsoo Ltd and while we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.</p>

    <p>In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.</p>

    <p>Through this website you are able to link to other websites which are not under the control of Itsoo Ltd. We have no control over the nature, content and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.</p>

    <p>Every effort is made to keep the website up and running smoothly. However, Itsoo Ltd takes no responsibility for, and will not be liable for, the website being temporarily unavailable due to technical issues beyond our control.</p>


    <h2>About Us</h2>

    <p>This website is owned by Itsoo Ltd</p>

    <p>Registered in England under number 8319519</p>

    <p>Registered Office: Box 543, 14 London Road, Guildford, GU12AG</p>

  </div>
</div>

app/views/front/validate_email_credit.html.erb
<br /><br /><br />
<div class="container_12 pages">
<%  if current_user%>
<h1>Welcome Back</h1>
<p>Please click <%= link_to 'here to view your credit >', root_url %></p>

<%else%>
<h1>Welcome to Who Actually</h1>
<p>To get your credit approved you will need to <%= link_to "log in or join us via Facebook.", "/auth/facebook", id: "login_with_facebook" %></p> 

<%end%>
</div>

app/views/front/validate_new_email_credit.html.erb
<br /><br /><br />
<div class="container_12 pages">
<%  if current_user%>
<h1>Welcome Back</h1>
<p>You credit has been added. <%= link_to 'Home >', root_url %></p>

<%else%>
<h1>Welcome to Hoovue</h1>
<p>To get your credit approved you will need to <%= link_to "log in or join us via Facebook.", "/auth/facebook", id: "login_with_facebook" %></p> 

<%end%>
</div>