config/routes.rb
Hoo::Application.routes.draw do
  



  get "connection/index", as: :connections
  

  resources :platforms


  get "beta/index"

  get "beta/work"

  get "beta/user"
  
  get "beta/add_credit"
  
  get "front/stats"

  resources :emails


  get "front/index"
  get "front/validate_email_credit"
  get "front/validate_new_email_credit"
  resources :betausers
  
  resources :betasessions
  
  resources :friendships
  resources :messages

  resources :posts


  resources :product_genres


  resources :credit_validations do
    member do
      put :validate
      put :flag
      put :validation
    end
  end


  resources :credits do
    collection do
      get :recent
      post :import 
      match 'role'
      match 'search'
      match 'batch'
      put :claim
    end
    member do
      put :increase
      put :flag
      put :claim
    end
  end


  resources :products, execpt: [:index, :destroy] do

    member do
      post :invite
    end

    collection do
      get :recent
      get :popular
    end
    #member do
    #get 'like'
    #get 'complete'
    #end
  end


#Rails Admin
mount RailsAdmin::Engine => '/lecrabe', :as => 'rails_admin'


#Session Routes
get "sessions/new"


#User Routes
resources :users
match 'auth/:provider/callback', to: 'sessions#create'
match 'auth/failure', to: redirect('/')
match 'signout', to: 'sessions#destroy', as: 'signout'
match 'users', to: 'users#index', as: 'users'


#Products
match '/rate' => 'rater#create', :as => 'rate'

#Search

match "search", to: 'search#index', :as => 'search'

#Temp 
get "holding/index"

match "message_preview", to: 'credits#validate-message', :as => 'message_preview'
#Front

match "legal", to: 'front#legal', :as => 'legal'
get :terms, to: "front#terms"
get :privacy, to: "front#privacy"
match "suggested", to: 'front#suggested', :as => 'suggested'

root :to => "beta#index"

 
end

app/views/shared/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38356982-1']);
  _gaq.push(['_trackPageview']);

  (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
   })();

</script>

app/views/shared/_error_messages.html.erb
<% if target && target.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(target.errors.count, "error") %> prohibited this form from being saved:</h2>

    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<% if flash[:error] %>
  <p class="error"><%= flash[:error] %></p>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="container_12">

    <div class="grid_4 left">
      <a href="#" class="social"><i class="fa fa-twitter fa-fw"></i> Follow us on Twitter</a>
      <a href="#" class="social"><i class="fa fa-facebook-square fa-fw"></i> Like us on Facebook</a>

      <%= image_tag '/assets/beta/logo-dark.png' %>
      <p>&copy; Copyright 2014</p>
      <%= link_to "Terms & Conditions", terms_path %>
      <%= link_to "Privacy Policy", privacy_path %>
    </div>

    <div class="grid_4">
      <h3>Top 5 Most Viewed</h3>
      <ol>
        <% Product.top_five.each do |product| %>
        <li>
            <%= link_to product_path(product) do %>
            <%= image_tag(product.image || '/assets/beta/placeholder-cover.png', :class => 'project') %>
            <h5><%= product.title %></h5>
            <p><%= product.platforms %></p>
        <% end %>
        </li>
      <% end %>
      </ol>
    </div>

    <div class="grid_4">
      <h3>Top 5 Most Credited</h3>
      <ol>
        <% User.top_five.each do |user| %>
          <li>
            <%= link_to user_path(user) do %>
              <%= image_tag '/assets/beta/placeholder-user.png', :class => 'user' %>
              <h5 class="name"><%= user.name %></h5>
              <!-- <p><%= (user.bio || "")[0..35] %></p> -->
              <span class="credits"><%= user.credits_count %>
                <span class="fa-stack">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-check fa-stack-1x white"></i>
                </span>
              </span>
            <% end %>
          </li>
        <% end %>
      </ol>
    </div>

  </div>
</div>

app/views/shared/_header.html.erb
<div class="header-container">
  <div class="container_12 header-content">

    <div class="logo grid_9">
      <div class="icon">
      <%= link_to root_url do %>
        <%= image_tag'/assets/beta/logo-icon.png' %>
      <% end %>
      </div>
      <div class="search">
        <%= form_tag search_credits_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search], :placeholder => "Find a game, person and more..." %>
        <% end %>
      </div>
    </div>

    <% if current_user %>
      <div class="grid_3 name">
        <%= link_to user_path(current_user) do %>
          <%= current_user.name %>
        <% end %>
      </div>
    <% end %>

    <div class="grid_3 signin">
      <% if current_user %>
        <%= link_to "Sign out", signout_path, class: "out" %>
      <% else %>
        <%= link_to "Login / Register", "/auth/facebook", id: "login_with_facebook" %>
      <% end %>
    </div>

  </div>
</div>

app/views/shared/_profile_image.html.erb
<div class="profile_img">
  <%= profile_image_tag credit.user, nil, {:class => 'user'} %>
  <% if credit && credit.confirmed? %>
    <span class="fa-stack verified">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-check fa-stack-1x white"></i>
    </span>
  <% end %>
</div>