config/routes.rb
Hoo::Application.routes.draw do
  



  get "connection/index", as: :connections
  

  resources :platforms


  get "beta/index"

  get "beta/work"

  get "beta/user"
  
  get "beta/add_credit"
  
  get "front/stats"

  resources :emails


  get "front/index"
  get "front/validate_email_credit"
  get "front/validate_new_email_credit"
  resources :betausers
  
  resources :betasessions
  
  resources :friendships
  resources :messages

  resources :posts


  resources :product_genres


  resources :credit_validations do
    member do
      put :validate
      put :flag
      put :validation
    end
  end


  resources :credits do
    collection do
      get :recent
      post :import 
      match 'role'
      match 'search'
      match 'batch'
      put :claim
    end
    member do
      put :increase
      put :flag
      put :claim
    end
  end


  resources :products, execpt: [:index, :destroy] do

    member do
      post :invite
    end

    collection do
      get :recent
      get :popular
    end
    #member do
    #get 'like'
    #get 'complete'
    #end
  end


#Rails Admin
mount RailsAdmin::Engine => '/lecrabe', :as => 'rails_admin'


#Session Routes
get "sessions/new"


#User Routes
resources :users
match 'auth/:provider/callback', to: 'sessions#create'
match 'auth/failure', to: redirect('/')
match 'signout', to: 'sessions#destroy', as: 'signout'
match 'users', to: 'users#index', as: 'users'


#Products
match '/rate' => 'rater#create', :as => 'rate'

#Search

match "search", to: 'search#index', :as => 'search'

#Temp 
get "holding/index"

match "message_preview", to: 'credits#validate-message', :as => 'message_preview'
#Front

match "legal", to: 'front#legal', :as => 'legal'
get :terms, to: "front#terms"
get :privacy, to: "front#privacy"
match "suggested", to: 'front#suggested', :as => 'suggested'

root :to => "beta#index"

 
end

app/controllers/beta_controller.rb
class BetaController < ApplicationController

  helper :all

  def index
    @featured_products = Product.where(title: ["Grand Theft Auto V", "Battlefield 4",  "Call of Duty: Black Ops"]).order("title")
    @popular_products = Product.most_popular
    @recent_products = Product.most_recents
    @recent_credits = Credit.most_recents
  end

  def work
    @product = Product.find_by_id(79)
    @credits = Credit.find_all_by_id([101,20,102])
    @credit = Credit.new
    @credit_validation = CreditValidation.new
    @post = Post.new
  end

  def user
    @user = User.find_by_id(2)
    @credits = Credit.where(:user_id => 2)

  end
end

app/helpers/beta_helper.rb
module BetaHelper
end

app/views/beta/_credit_mini.html.erb
<div class="project project-image" style="background-image: url('<%= (credit.product.image || '/assets/beta/placeholder-cover.png') %>'); "></div>
<h5><%= link_to credit.user.name, user_path(credit.user) %></h5>
<p><%= credit.role %></p>
<h6><%= link_to credit.product.title, product_path(credit.product) %></h6>

<%= render "shared/profile_image", user: credit.user, credit: credit %>

app/views/beta/_product_mini.html.erb
<div class="project project-image" style="background-image: url('<%= (product.image || '/assets/beta/placeholder-cover.png') %>'); "></div>
<h5><%= link_to product.title, product_path(product) %></h5>
<h6><%= product.platforms %></h6>

<% if product.credits.any? %>
  <ul class="team">
    <% product.credits.uniq_user.limit(3).each do |credit| %>
      <li class="profile_img">
        <%= image_tag((credit.user.profile_picture  || '/assets/beta/placeholder-user.png'), :class => 'user') %>
        <span class="fa-stack verified">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-check fa-stack-1x white"></i>
        </span>
      </li>
    <% end %>
    <% if product.credits.uniq_user.count > 3 && product.credits.uniq_user.count < 100 %>
      <li class="profile_more">+<%= product.credits.uniq_user.count %></li>
    <% elsif product.credits.uniq_user.count > 100 %>
      <li class="profile_more">•••</li>
    <% end  %>
  </ul>
<% end %>

app/views/beta/add_credit.html.erb
<ul id="tabs">
		    <li><a href="#" name="tab1">Overview</a></li>
    		<li><a href="#" name="tab2">Tech Specs</a></li>
			<li><a href="#" name="tab3	">Performance</a></li>
			<li><a href="#" name="tab4">Compare</a></li>
			<li><a href="#" name="tab5">Downloads</a></li>
    		<li><a href="#" name="tab6">Get d3</a></li>   
		</ul>	
		
				<div id="content"> 
				    <div id="tab1">

						Test

				
</div>
</div>
		

app/views/beta/index.html.erb
<div class="index">


  <!-- New Hero Area -->
  <div class="hero">

    <ul class="backgrounds">
      <li></li>
      <li></li>
      <li></li>
    </ul>

    <div class="project_slider">

      <% @featured_products.each do |product| %>
        <div>
          <div class="container_12">
            <h5><%= product.title %></h5>
            <div class="project_details" data-product-url="<%= product_url(product, anchor: 'add_credit') %>">
              <%= product_image_tag product, {size: :post}, {class: "cover_art"} %>
              <ul class="team">
                <% product.credits.limit(3).each do |credit| %>
                  <li>
                    <%= render "/shared/profile_image", user: credit.user, credit: credit %>
                    <div class="profile_info">
                      <span class="profile_name"><%= credit.name %></span>
                      <span class="profile_role"><%= credit.role %></span>
                      <%= content_tag(:p, credit.role_desc, class: "profile_description") %>
                    </div>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      <% end %>

    </div> <!-- Close project_slider -->

    <div class="container_12">

      <a href="#" id="add-credit" class="add_credit hidden">
          <i class="fa fa-plus"></i>
      </a>

      <div class="grid_8 intro">
        <h1 class="hero-h1"><span class="logotype">WhoActually</span> <span class="phrase"></span></h1>

        <p>Beyond a job title — Find out who did what on a particular game, film and more...
          Scout talent, read insider stories or claim credit for your own role.</p>

        <a href="#" class="btn"><i class="fa fa-play-circle"></i> See how it works</a>

      </div> <!-- Close grid_6 -->
    </div> <!-- Close container_12 -->

    <div class="bottom_bar">
    </div>

  </div> <!-- Close hero -->

  <!-- Video Overlay -->
  <div class="video">
    <iframe src="http://player.vimeo.com/video/70016170?byline=0&amp;portrait=0&amp;color=00cc99" width="800" height="450" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
  </div>

  <div class="lists">
    <div class="container_12">
      <div class="grid_4">
        <h3>Recent Projects</h3>
        <ul>
          <% @recent_products.each do |product| %>
            <li><%= render "product_mini", product: product %></li>
          <% end %>
        </ul>
        <%= link_to "view more", recent_products_path, class: "more" %>
      </div>

      <div class="grid_4">
        <h3>Most Popular</h3>
        <ul>
          <% @popular_products.each do |product| %>
            <li><%= render "product_mini", product: product %></li>
          <% end %>
        </ul>
        <%= link_to "view more", popular_products_path, class: "more" %>
      </div>


      <div class="grid_4">
        <h3>Recent Credits</h3>
        <ul class="credits">
          <% @recent_credits.each do |credit| %>
            <li><%= render "credit_mini", credit: credit %></li>
          <% end %>
        </ul>
        <%= link_to "view more", recent_credits_path, class: "more" %>
      </div>
    </div> <!-- Close container_12 -->

  </div> <!-- Close lists -->

</div>

app/views/beta/user.html.erb
<div class="container_12 user-page">
	<div class="grid_9 alpha user-container">





<div class="user-info-panel">
	
	<div class="grid_3 profile-picture">
		<% if @user.picture.blank? %>

		<% if @user.provider == "facebook" %>		
	<img src="http://graph.facebook.com/<%= @user.uid%>/picture?type=large"><br />
		<% end %>
		<% if @user.provider == "linkedin" %>		
	<%= image_tag @user.profile_picture %><br />
		<% end %>
		<% else %>
		<%= image_tag @user.picture %>
		<% end %>
		
	</div>
	
	
	<div class="grid_3 stats">
		<div class="stats">
			<p class="credit-count">14</p>
			<p class="credits">Credits</p>
				<div class="verified-count">
					<p class="verified-credits">10</p>
					<p class="verifed">Verified</p>
				</div>
					<div class="images">
						<p class="verified-credits">10</p>
						<p class="verifed">Videos</p>
					</div>
						<div class="videos">
							<p class="verified-credits">10</p>
							<p class="verifed">Images</p>
						</div>
		</div>
	</div>
	
	<div class="grid_2 analytics">
		<div class="followers">
			<div class="data">
				11
			</div>
			<div class="title">
				Followers
			</div>	
			</div>
			
			<div class="likes">
				<div class="data">
					11
				</div>
				<div class="title">
					Likes
				</div>	
				</div>
				
				
				<div class="shared">
					<div class="data">
						11
					</div>
					<div class="title">
						Shared
					</div>	
				</div>
					
					
					<div class="views">
						<div class="data">
							11
						</div>
						<div class="title">
							Views
						</div>	
					</div>			
					
	
	 </div>
	 
	<div class="description">
		<div class="name">
			<%= @user.name %>
		</div>
	
		<a href="#" class="blue-btn">Follow <%= image_tag '/assets/beta/follow.png' %></a>
	
		<div class="info">
			<p class="url"><%= @user.link %></p>
		
		</div>	
		
		<div class="bio">
			<%= @user.bio %>
		</div>	
			
		
			
		
	
	</div>
		
	
</div>	

<ul id="tabs">
		    <li><a href="#" name="tab1">Overview</a></li>
    		<li><a href="#" name="tab2">Tech Specs</a></li>
			<li><a href="#" name="tab3	">Performance</a></li>
			<li><a href="#" name="tab4">Compare</a></li>
			<li><a href="#" name="tab5">Downloads</a></li>
    		<li><a href="#" name="tab6">Get d3</a></li>   
		</ul>	
		
		

<div class="credits">
	
	<% @credits.each do |c| %>
	<div class="credit-item">
		<% if c.user %>
	<%= image_tag c.product.image, :width => "50" %>	 
	<div class="user-name">
	<%= link_to c.product.title, product_path(c.product) %>
	</div>
	
	<div class="user-details">
		<p class="title">Credits</p><p class="data"><%= c.user.credits_count %></p>
		<p class="title">Followers</p><p class="data">5</p>
	</div>
	
	<div class="more-detail">
		<p class="role"><%= c.role %></p>
		<p class="role-description"><%= c.role_desc %></p>
	</div>
	
	
	<script type="text/javascript">
 
	$(document).ready(function(){
 
	        $(".slidingDiv_interesting_fact_<%= c.id %>").hide();
	        $(".show_hide_interesting_fact_<%= c.id %>").show();
 
	    $('.show_hide_interesting_fact_<%= c.id %>').click(function(){
	    $(".slidingDiv_interesting_fact_<%= c.id %>").slideToggle();
	    });
 
	});
 
	</script>

	
	<div class="interesting_fact">
		<a href"#" class="show_hide_interesting_fact_<%= c.id %>">View Insider Stories</a>
	</div>
	
	
	
	<div class="validation-info">
	<p class="cv-count">
	<% if c.confirmed_validations_count > 2 %>
	<%= image_tag '/assets/beta/tick.png' %>
	<% else %>	
		<%= c.confirmed_validations_count %>/3</p><br />
		
	<% end %>	
	<p class="validation-status">
		<% if c.confirmed_validations_count > 2  %>
		Verified</p>
		<% else %>
		Partly Verified
		<% end %>
	
	
<div class="head-shots">
		<% if c.credit_validations.empty? %>
			<% 3.times do %>
			<a class="show_hide_validate_partial_<%= c.id.to_i %>">
			<span class="picture">
			<% if current_user %>
				<% if current_user.id == c.user_id  %>
					<%= image_tag '/assets/empty.png' %>
				<% else %>	
				<%= image_tag '/assets/question.png' %>	
				<% end %>
				<% else %>
				<%= image_tag '/assets/question.png' %>
				<% end %>
			</span>
			</a>
			<% end %>
			<% if current_user %>
				<% if current_user.id == c.user_id  %>
		
					<% end %> <% end %>
			<% else %>

		<% end %>
	
		
	
					<% if c.credit_validations.count.eql?(1) %>
					<span class="tick-text" style="">Who will actually vouch for me: </span><br />
		<% c.credit_validations.each do |cv| %>
		<% if cv.status == "confirmed" %>
		<span class="picture">
			<% @user = User.find_by_id(cv.validator_id) %>
		<a href="/users/<%= cv.validator_id %>" name="confirmed1"><img src="http://graph.facebook.com/<% if @user %><%= @user.uid %><% end %>/picture?type=square" style="margin-top:-5px;"></a>
		</span>
	
		<% end %>
			<% if cv.status == "pending" %>
			<span class="picture">
				<% if current_user %>
					<% if current_user.id == c.user_id  %>
				<%= link_to credit_validation_path(cv) do %>
			<%= image_tag '/assets/pending.png' %>
	
				<% end %>
				<% else %>
					<%= image_tag '/assets/pending.png' %>
						<% end %>
						<% else %>
							<%= image_tag '/assets/pending.png' %>
							<% end %>
			
				</span>
		
		
		
	
			<% end %>
			<% 2.times do %>
			<a class="show_hide_validate_partial_<%= c.id %>">
			<span class="picture">
			<% if current_user %>	
				<% if current_user.id == c.user_id  %>
					<%= image_tag '/assets/empty.png' %>
				<% else %>	
				<%= image_tag '/assets/question.png' %>	
				<% end %>
				<% end %>
			
				
			</span>
			</a>
			<% end %>
			<% if current_user %>
				<% if current_user.id == c.user_id  %>
		
					<% end %> <% end %>
			<% end %>
			<% else %>
	
	<% end %>

	<% if c.credit_validations.count.eql?(2)  %>
	<% c.credit_validations.each do |cv| %>
	<% if cv.status == "confirmed" %>
	<span class="picture">
		<% @user = User.find_by_id(cv.validator_id) %>
	<a href="/users/<%= cv.validator_id %> "name="confirmed2"><img src="http://graph.facebook.com/<% if @user %><%= @user.uid %><% end %>/picture?type=square" style="margin-top:-5px;"></a>

	</span>
	<% end %>
		<% if cv.status == "pending" %>
	
		<span class="picture">
			<% if current_user %>
				<% if current_user.id == c.user_id  %>
			<%= link_to credit_validation_path(cv) do %>
		<%= image_tag '/assets/pending.png' %>
	
			<% end %>
			<% else %>
				<%= image_tag '/assets/pending.png' %>
					<% end %>
					<% else %>
						<%= image_tag '/assets/pending.png' %>
						<% end %>
	
			</span>
	<% end %>

		
		<% end %>
		<% 1.times do %>
		<a class="show_hide_validate_partial_<%= c.id %>">
			<span class="picture">
			<% if current_user %>	
				<% if current_user.id == c.user_id  %>
					<%= image_tag '/assets/empty.png' %>
				<% else %>	
				<%= image_tag '/assets/question.png' %>	
				<% end %>
				<% end %>
			</span>
	
		</a>
		<% if current_user %>
			<% if current_user.id == c.user_id  %>
	
				<% end %> <% end %>
		<% end %>
	
		<% end %>
	
		<% if c.credit_validations.count.eql?(3)  %>
		<% c.credit_validations.each do |cv| %>
	
		<% if cv.status == "confirmed" %>
		<span class="picture">
			<% @user = User.find_by_id(cv.validator_id) %>
		<a href="/users/<%= cv.validator_id %>" name="confirmed3"><img src="http://graph.facebook.com/<% if @user %><%= @user.uid %><% end %>/picture?type=square" style="margin-top:-5px;"></a>
		</span>
		<% end %>
			<% if cv.status == "pending" %>
		<span class="picture">
			<% if current_user %>
				<% if current_user.id == c.user_id  %>
			<%= link_to credit_validation_path(cv) do %>
		<%= image_tag '/assets/pending.png' %>
	
			<% end %>
			<% else %>
				<%= image_tag '/assets/pending.png' %>
					<% end %>
					<% else %>
						<%= image_tag '/assets/pending.png' %>
						<% end %>
		
			</span>
		
			<% end %>

		
			<% end %>
	
	
			<% end %>
	
	
	
</div>	
	
	
	
	
	
	
	
	
	</div>
	
		<% end %>
	</div>
		
		<div class="slidingDiv_interesting_fact_<%= c.id %>" id="interesting_fact">
			<h3>Insider Stories:</h3>
				 <% if current_user %>			
<% if current_user.id == c.user_id %><%= link_to "(edit)", edit_credit_path(:id => c) %> <% end %> <% end %>
<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://alpha.whoactually.com/products/<%=  c.product.id %>" data-text="<%= c.fact %>">Tweet this fact</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</h3><p><%= c.fact %></p>



<% if c.product.status == "In Development" or c.product.status == "Live and Ongoing"  %>	


<h3>Updates:</h3>
	  <% @posts = Post.where(:credit_id => c.id).order("created_at desc").limit(4) %>
<% if current_user %>			
	<% if current_user.id == c.user_id %>	
			<%= form_for(@post) do |f| %>
			  <% if @post.errors.any? %>
			    <div id="error_explanation">
			      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

			      <ul>
			      <% @post.errors.full_messages.each do |msg| %>
			        <li><%= msg %></li>
			      <% end %>
			      </ul>
			    </div>
			  <% end %>
			  <div class="field">
			    <%= f.label :post_an_update %><br />
			    <%= f.text_area :body, :rows => "5" %>
				<%= f.hidden_field :credit_id, :value => c.id %>
			  </div>
			  <div class="actions">
			    <%= f.submit "Add update", :class => "blue-link" %>
			 
					<% end %>
				<% end %>	
			<% end %>
		<% end %>
		</div>	
	<% end %>
	
</div>

	
</div>



<div class="grid_3 activity-feed">

	<h3>Recent Activity</h3>
	
<% for friendship in current_user.friendships%>
<% @friend_credits = Credit.where(:user_id => friendship.friend.id).limit(4) %>
<% @friend_credits.each do |fc| %>
<div class="following-item">

	<div class="profile-picture">
		<%= image_tag friendship.friend.profile_picture %>
	</div>
	
	<div class="name">
	<%= link_to user_path(friendship.friend.id) do %><%= friendship.friend.name %><% end %>
	</div>
	<div class="stats">
	<p>Credits</p> <div class="data">
	 <%= friendship.friend.credits_count %>
	</div>
	</div>	
<div class="role">
		<%= fc.role %>
	</div>
	<div class="product-title">
	<%= fc.product.title %>
	</div>
</div>
<% end %>
<% end %>



  <% for user in current_user.inverse_friends %>
<%= link_to user_path(user.id) do %><%=h user.name %><% end %><br />
  <% end %>



		
</div>

</div>