config/routes.rb
Hoo::Application.routes.draw do
  



  get "connection/index", as: :connections
  

  resources :platforms


  get "beta/index"

  get "beta/work"

  get "beta/user"
  
  get "beta/add_credit"
  
  get "front/stats"

  resources :emails


  get "front/index"
  get "front/validate_email_credit"
  get "front/validate_new_email_credit"
  resources :betausers
  
  resources :betasessions
  
  resources :friendships
  resources :messages

  resources :posts


  resources :product_genres


  resources :credit_validations do
    member do
      put :validate
      put :flag
      put :validation
    end
  end


  resources :credits do
    collection do
      get :recent
      post :import 
      match 'role'
      match 'search'
      match 'batch'
      put :claim
    end
    member do
      put :increase
      put :flag
      put :claim
    end
  end


  resources :products, execpt: [:index, :destroy] do

    member do
      post :invite
    end

    collection do
      get :recent
      get :popular
    end
    #member do
    #get 'like'
    #get 'complete'
    #end
  end


#Rails Admin
mount RailsAdmin::Engine => '/lecrabe', :as => 'rails_admin'


#Session Routes
get "sessions/new"


#User Routes
resources :users
match 'auth/:provider/callback', to: 'sessions#create'
match 'auth/failure', to: redirect('/')
match 'signout', to: 'sessions#destroy', as: 'signout'
match 'users', to: 'users#index', as: 'users'


#Products
match '/rate' => 'rater#create', :as => 'rate'

#Search

match "search", to: 'search#index', :as => 'search'

#Temp 
get "holding/index"

match "message_preview", to: 'credits#validate-message', :as => 'message_preview'
#Front

match "legal", to: 'front#legal', :as => 'legal'
get :terms, to: "front#terms"
get :privacy, to: "front#privacy"
match "suggested", to: 'front#suggested', :as => 'suggested'

root :to => "beta#index"

 
end

app/models/credit.rb
class Credit < ActiveRecord::Base

  attr_accessible :product_id, :user_id, :product, :user,
    :role, :credit_validations_count, :role_desc, :current_credit_role,
    :confirmed_validations_count, :credit_validation_id, :issue, :validator_id,
    :user_name, :current_credit_id, :fact, :credit_validations_attributes,
    :status, :pending_user_email, :count, :startdate, :enddate, :release,
    :category, :product_idd, :tag_list, :promoted, :source

  attr_accessor :current_credit_id, :current_credit_role, :product_idd 

  belongs_to :user, :counter_cache => true
  belongs_to :product, :counter_cache => true
  has_many :credit_validations, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  accepts_nested_attributes_for :credit_validations, allow_destroy: true


  #validates_presence_of :role
  #validates_uniqueness_of :pending_user_email, :scope => [:credit_validation_id, :product_id ], :message => "A credit with this email and role has already been taken."
  #validates_uniqueness_of :user_id, :scope => [:role, :product_id], :message => "A credit with this email and role has already been taken."

  scope :confirmed, where(:status => "confirmed")
  scope :pending, where(:status => "pending")
  scope :cv_unverified, where(:credit_validations_count => "0")
  scope :cv_part, where(:confirmed_validations_count => "1 | 2")  
  scope :cv_confirmed, where(:confirmed_validations_count => "3")
  scope :user_pending, lambda { |user| where("credit.user_id = ?", user.id) }
  scope :wa_source, where(source: "wa")  

  scope :claimable, -> { where confirmed_validations_count: 0 }

  scope :most_recents, -> { confirmed.order('created_at ASC').limit(3) } 
  scope :recent, -> { confirmed.order('created_at ASC') }
  scope :uniq_user, -> { select('DISTINCT credits.user_id, *') } 

  delegate :name, to: :user

  def confirmed?
    status == "confirmed"
  end

  def pending?
    status == "pending"
  end

  def fact_short
    return fact[0, 50] + "..." if fact
    "..."
  end


  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Credit.create! row.to_hash
    end
  end

end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController

  load_and_authorize_resource
  skip_authorize_resource :only => :search

  def index
    @credits = Credit.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @credits }
    end
  end

  def recent
    @credits = Credit.recent.limit(25)
    @page_title = "Recent Credits"
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @credits }
    end
  end

  def import #Remove?
    Credit.import(params[:file])
    redirect_to root_url, notice: "credits imported."
  end

  def show
    @credit = Credit.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @credit }
    end
  end

  def new
    @credit = Credit.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @credit }
    end
  end

  def edit
    session[:return_to] = request.referer
    @credit = Credit.find(params[:id])
  end

  def role
    session[:return_to] = request.referer
    @credit = Credit.find(params[:id])
    1.times do
      credit_validation = @credit.credit_validations.where(:user_id => current_user.id)
    end   
  end

  def search
    if params[:search].blank?
      flash.now[:notice] = "You must search for Games or People"
      @products = []
      @users = []
    else
      @products = Product.search(params[:search]).page(params[:page])
      @users = User.search(params[:search]).page(params[:page])
    end

    if current_user 
      @credit = Credit.new
      @product = Product.new
    end  
  end

  def flag
    @credit = Credit.find(params[:id])
    @credit_validation = CreditValidation.find_by_id(@credit.credit_validation_id)
    @credit_validation.status = "pending"
    @credit_validation.save
    flash[:notice] = "Thank you we will look into it."
    redirect_to root_url
  end

  def batch
    @credit = Credit.new
  end


  def create #Needs refactoring and moving

    #Init new credit pass params and defaults

    @credit = Credit.new(params[:credit])
    @credit.role = params[:role]
    @credit.source = "wa"
    @credit.confirmed_validations_count = 0 #Migration for default value
    @credit.credit_validation_count = 0 #Migration for default value
    #@credit.product_id = @credit.product_idd

    #Batch credit add - View now removed - Review with Ed 

    if params[:batch] #Can be removed?
      @credit.role = params[:role]
      @credit.product_id = params[:product_id]
      @credit.current_credit_role = params[:current_credit_role]
      @credit.user_id = current_user.id
    end

    #Set credit tokens 

    @credit.pending_token = SecureRandom.urlsafe_base64(20) #Create random pending token
    #if @credit.pending_user_email == current_user.email # Quick validation check
      #redirect_to :back, notice: 'You cannot validate yourself.'
    else
      if params[:facebook]
        @credit.validator_id = current_user.id
        @credit.pending_user_email = rand(10000...30000).to_i # Create random pending token
      end


      #if params[:email]
      #@credit.product_id = @credit.product_idd
      #end


      #Create new CV and set values

      @credit_validation = CreditValidation.new(params[:credit_validation])
      @credit_validation.status = "pending"
      @credit.validator_id = current_user.id
      @credit_validation.user_id = current_user.id #Redundant now? 
      @credit_validation.token = @credit.pending_user_email
      @credit_validation.validator_id = rand(10000...30000).to_i #Random so not nil
      @credit_validation.credit_id = @credit.current_credit_id

      respond_to do |format|
        if @credit.save
          if @credit_validation.save
            @credit.credit_validation_id = @credit_validation.id
            @credit.user_name = current_user.name
            @credit.update_attributes(params[:credit])
          end #DBNT

          if @credit.pending_user_email #Send alert if email
            CreditMailer.new_credit(@credit).deliver
          end

          if params[:batch] #Redundant? See above.
            format.html { redirect_to :back, notice: 'Credit was successfully created.' }
          end 

          if params[:facebook] #Facebook diag redirect. Replaced with FB inside app but removed due to permissions. Re-visit. 
            format.html { redirect_to ("https://www.facebook.com/dialog/send?app_id=#{ENV['FACEBOOK_APP_ID']}&name=whoactually.com%20credit%20-%20Get%20the%20recognition%20you%20deserve&description=As%20a%20co-creator%20on%20#{@credit.product.title},%20#{current_user.name}%20would%20like%20you%20to%20validate%20their%20credit.%20#{current_user.name}%20also%20recorded%20that%20you%20were%20#{@credit.role}.%20To%20validate%20this%20credit%20and%20claim%20your%20own%20follow%20this%20link.&link=http://#{ENV['DEFAULT_URL']}/credits/#{@credit.id}?pending_token=#{@credit.pending_token}&redirect_uri=http://#{ENV['DEFAULT_URL']}/users/#{current_user.id}")}
          end 

          #Redirect to suggested product
          #format.html  { redirect_to("/suggested?product_id=#{@credit.product_id}") }
          format.html { redirect_to(product_path @credit.product) }
        else
          flash[:error] =  @credit.errors.full_messages.each do |msg| msg.gsub(/\W+/, '')  end 
          format.html { redirect_to :back }
          format.json { render json: @credit.errors, status: :unprocessable_entity }
        end
      end
    #end
  end


  def update
    @credit = Credit.find(params[:id])

    respond_to do |format|
      if @credit.update_attributes(params[:credit])

        format.html { redirect_to user_path(current_user), notice: 'Your Credit has been updated' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @credit = Credit.find(params[:id])
    @credit.destroy

    respond_to do |format|
      format.html { redirect_to :back, notice: 'Credit deleted' }
      format.json { head :no_content }
    end
  end


  def claim #Claim and rediect suggested credits
    Credit.update_all({user_id: @current_user.id, :confirmed_validations_count => "0", :source => "wa"}, {id: params[:credit_ids]})
    redirect_to :back
  end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/_credit.html.erb
<%= div_for comment, data: {id: comment.id} do %>
  <p><strong><%= comment.name %> says</strong></p>
  <%= simple_format comment.content %>
<% end %>

app/views/credits/_credit_fields.html.erb
<%= f.text_field :role %>
<%= f.text_field :fact %>
<%= f.hidden_field :user_id, :value => current_user.id %>
<%= f.submit %>

app/views/credits/_credits_list.html.erb
<ul class="products">
  <% credits.each do |credit| %>
    <li class="product credit">

      <%= link_to credit.user.name do %>
        <%= product_image_tag credit.product, {size: :small}, {class: "cover_art"} %>
        <%= render "shared/profile_image", user: credit.user, credit: credit %>
        <h3><%= credit.user.name %></h3>
        <span><%= credit.role %></span>
        <span><%= credit.product.title %></span>

      <% end %>

    </li>
  <% end %>
</ul>

app/views/credits/_more-detail.html.erb
		<div class="more-detail">		
		<% if c.product.status == "In Development" %>	
		<h3>What you are actually doing:<% else %>	
		<h3>What I actually did:<% end %> <% if current_user %>			
<% if current_user.id == c.user_id %> <%= link_to "(edit)", role_credits_path(:id => c) %> <% end %> <% end %> </h3><p>  <%= c.role_desc %></p>	
			<h3>Insider Stories:
				 <% if current_user %>			
<% if current_user.id == c.user_id %><%= link_to "(edit)", edit_credit_path(:id => c) %> <% end %> <% end %>
<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://alpha.whoactually.com/products/<%=  c.product.id %>" data-text="<%= c.fact %>">Tweet this fact</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</h3><p><%= c.fact %></p>



<% if c.product.status == "In Development" or c.product.status == "Live and Ongoing"  %>	


<h3>Updates:</h3>
	  <% @posts = Post.where(:credit_id => c.id).order("created_at desc").limit(4) %>
<% if current_user %>			
	<% if current_user.id == c.user_id %>	
			<%= form_for(@post) do |f| %>
			  <% if @post.errors.any? %>
			    <div id="error_explanation">
			      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

			      <ul>
			      <% @post.errors.full_messages.each do |msg| %>
			        <li><%= msg %></li>
			      <% end %>
			      </ul>
			    </div>
			  <% end %>
			  <div class="field">
			    <%= f.label :post_an_update %><br />
			    <%= f.text_area :body, :rows => "5" %>
				<%= f.hidden_field :credit_id, :value => c.id %>
			  </div>
			  <div class="actions">
			    <%= f.submit "Add update", :class => "blue-link" %>
			 
			<% end %>
	<% end %>	
		<% end %>
	<div class="update">
	<ul>	
	<% @posts.each do |post| %>
	<li>
		<%= post.created_at.strftime "%d-%m-%Y" %><br />
		<%= post.body %>
	</li>
	
	<% end %>
	</ul>	
	</div>
			<% end %>
	
		</div>

app/views/credits/_search_results.html.erb
<% if @products.present? %>	
<h2><i class="fa fa-archive"></i> Games</h2>

  <ul>
    <% @products.each do |p| %>
      <li>
        <%= link_to p do %>
          <% if p.image? %>
            <%= image_tag p.image.thumb.to_s, :class => 'cover_art' %>
          <% else %>
            <%= image_tag '/assets/beta/placeholder-cover.png', :class => 'cover_art'%>
          <% end %>
          <h3><%= p.title %></h3>
          <span>
            <% if p.product_genre_id.present? %>
              <%= p.product_genre.name %>
            <% end %>
          </span>
        <% end %>
      </li>
    <% end %>	
  </ul>
  <%= paginate @products %>
<% end %>

<% if @users.present? %>
  <h2><i class="fa fa-users"></i> People</h2>

  <ul class="people">
    <% @users.each do |u| %>
      <li>
        <%= link_to u do %>
          <% if u.provider == "facebook" %>
            <img src="http://graph.facebook.com/<%= u.uid%>/picture?type=square" class="user">	
          <% else %>
            <% if u.profile_picture %>
              <%= image_tag u.profile_picture, :class => 'user' %>
            <% else %>
              <%= image_tag '/assets/beta/placeholder-user.png', :class => 'user' %>
            <% end %>
          <% end %>

          <h3><%= u.name %></h3>

        <% end %>
      </li>
    <% end %>
  </ul>

  <%= paginate @users %>
<% end %>

<% if @projects.blank? &&  @users.blank? %>
  <div class="noresults">
  <p>Sorry, your search returned no results. <br>We may not yet have it in our database.</p>
  <p><%= link_to "Add a new game", new_product_path, class: "btn" %></p>
  </div>
<% end %>

app/views/credits/_ticks.html.erb
		
	<% if c.credit_validations.empty? %>
	
		<span class="tick-text" style="">Who will actually vouch for me: </span><br />
			
		<% 3.times do %>
		<a class="show_hide_validate_partial_<%= c.id.to_i %>">
		<span class="score">
		<% if current_user %>
			<% if current_user.id == c.user_id  %>
				<%= image_tag '/assets/empty.png' %>
			<% else %>	
			<%= image_tag '/assets/question.png' %>	
			<% end %>
			<% else %>
			<%= image_tag '/assets/question.png' %>
			<% end %>
		</span>
		</a>
		<% end %>
		<% if current_user %>
			<% if current_user.id == c.user_id  %>
		
				<% end %> <% end %>
		<% else %>

	<% end %>
	
		
	
				<% if c.credit_validations.count.eql?(1) %>
				<span class="tick-text" style="">Who will actually vouch for me: </span><br />
	<% c.credit_validations.each do |cv| %>
	<% if cv.status == "confirmed" %>
	<span class="score">
		<% @user = User.find_by_id(cv.validator_id) %>
	<a href="/users/<%= cv.validator_id %>" name="confirmed1"><img src="http://graph.facebook.com/<% if @user %><%= @user.uid %><% end %>/picture?type=square" style="margin-top:-5px;"></a>
	</span>
	
	<% end %>
		<% if cv.status == "pending" %>
		<span class="score">
			<% if current_user %>
				<% if current_user.id == c.user_id  %>
			<%= link_to credit_validation_path(cv) do %>
		<%= image_tag '/assets/pending.png' %>
	
			<% end %>
			<% else %>
				<%= image_tag '/assets/pending.png' %>
					<% end %>
					<% else %>
						<%= image_tag '/assets/pending.png' %>
						<% end %>
		<p style="margin:-10px;">Pending</p>
			</span>
		
		
		
	
		<% end %>
		<% 2.times do %>
		<a class="show_hide_validate_partial_<%= c.id %>">
		<span class="score">
		<% if current_user %>	
			<% if current_user.id == c.user_id  %>
				<%= image_tag '/assets/empty.png' %>
			<% else %>	
			<%= image_tag '/assets/question.png' %>	
			<% end %>
			<% end %>
			
				
		</span>
		</a>
		<% end %>
		<% if current_user %>
			<% if current_user.id == c.user_id  %>
		
				<% end %> <% end %>
		<% end %>
		<% else %>
	
<% end %>

<% if c.credit_validations.count.eql?(2)  %>
<span class="tick-text" style="">Who will actually vouch for me: </span><br />
<% c.credit_validations.each do |cv| %>
<% if cv.status == "confirmed" %>
<span class="score">
	<% @user = User.find_by_id(cv.validator_id) %>
<a href="/users/<%= cv.validator_id %> "name="confirmed2"><img src="http://graph.facebook.com/<% if @user %><%= @user.uid %><% end %>/picture?type=square" style="margin-top:-5px;"></a>

</span>
<% end %>
	<% if cv.status == "pending" %>
	
	<span class="score">
		<% if current_user %>
			<% if current_user.id == c.user_id  %>
		<%= link_to credit_validation_path(cv) do %>
	<%= image_tag '/assets/pending.png' %>
	
		<% end %>
		<% else %>
			<%= image_tag '/assets/pending.png' %>
				<% end %>
				<% else %>
					<%= image_tag '/assets/pending.png' %>
					<% end %>
	<p style="margin:-10px;">Pending</p>
		</span>
<% end %>

		
	<% end %>
	<% 1.times do %>
	<a class="show_hide_validate_partial_<%= c.id %>">
		<span class="score">
		<% if current_user %>	
			<% if current_user.id == c.user_id  %>
				<%= image_tag '/assets/empty.png' %>
			<% else %>	
			<%= image_tag '/assets/question.png' %>	
			<% end %>
			<% end %>
		</span>
	
	</a>
	<% if current_user %>
		<% if current_user.id == c.user_id  %>
	
			<% end %> <% end %>
	<% end %>
	
	<% end %>
	
	<% if c.credit_validations.count.eql?(3)  %>
	<% c.credit_validations.each do |cv| %>
	
	<% if cv.status == "confirmed" %>
	<span class="score">
		<% @user = User.find_by_id(cv.validator_id) %>
	<a href="/users/<%= cv.validator_id %>" name="confirmed3"><img src="http://graph.facebook.com/<% if @user %><%= @user.uid %><% end %>/picture?type=square" style="margin-top:-5px;"></a>
	</span>
	<% end %>
		<% if cv.status == "pending" %>
	<span class="score">
		<% if current_user %>
			<% if current_user.id == c.user_id  %>
		<%= link_to credit_validation_path(cv) do %>
	<%= image_tag '/assets/pending.png' %>
	
		<% end %>
		<% else %>
			<%= image_tag '/assets/pending.png' %>
				<% end %>
				<% else %>
					<%= image_tag '/assets/pending.png' %>
					<% end %>
	<p style="margin:-10px;">Pending</p>
		</span>
		
		<% end %>

		
		<% end %>
	
	
		<% end %>

app/views/credits/_validate-credit.html.erb
<% if current_user %>			
<% if current_user.id == c.user_id %>

<script type="text/javascript">
 
$(document).ready(function(){
 
        $(".slidingDiv_validate_partial_<%= c.id %>").hide();
        $(".show_hide_validate_partial_<%= c.id %>").show();
 
    $('.show_hide_validate_partial_<%= c.id %>').click(function(){
    $(".slidingDiv_validate_partial_<%= c.id %>").slideToggle();
    });
 
});
 
</script>


<script type="text/javascript">
 
$(document).ready(function(){
 
        $(".slidingDiv_email_<%= c.id %>").hide();
        $(".show_hide_email_<%= c.id %>").show();
 
    $('.show_hide_email_<%= c.id %>').click(function(){
    $(".slidingDiv_email_<%= c.id %>").slideToggle();
    });
 
});
 
</script>

<div class="slidingDiv_validate_partial_<%= c.id %>">
<% if c.credit_validations.count < 3  %>

	
	
<div class="credit-validate-container">
<div style="float:right;"> <a class="show_hide_validate_partial_<%= c.id %>">(close X)</a></div>
	<h2>Someone who already has a credit to verify yours</h2>
    <div class="help-box" stlye="margin-top:-20px">
		 <h4>Help</h4>
		To verify your credit ask someone else who had a role on <%= p.title %> to vouch for you
		</div>
	<%= form_for(@credit_validation) do |f| %>
	<%= f.label "Select co-creator:"%>
		<%= f.collection_select :credit_id, Credit.where('user_id != ?', current_user.id).where(:product_id => p.id).uniq, :id, :user_name, :prompt => "Please Select" %>
		<%= f.hidden_field :validator_id, :value => current_user.id %>
		<%= f.hidden_field :status, :value => "confirmed" %>
	   
		<%= submit_tag " SEND REQUEST", :name => 'existing_credit', :id => 'blue-link' %>
		<%= f.hidden_field :current_credit_id, :value => c.id %>
	<% end %>
</div>	
<h2 style="float:left; width:100%;">Or Invite someone to verify you from:</h2>
<a class="show_hide_email_<%= c.id %>" style="cursor: pointer;"><%= image_tag 'validate-by-email-button.png' %></a>
	<a class="show_hide_facebook_<%= c.id %>" style="cursor: pointer;" ><%= image_tag 'validate-by-facebook-button.png' %></a>
		
</div>


<div class="slidingDiv_email_<%= c.id %>">
	<div class="credit-validate-container">

<div style="float:right;"> <a class="show_hide_email_<%= c.id %>">(close X)</a></div>
<br />
	
<%= form_for @credit, :validate => true do |f|%>
<% if @credit.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

    <ul>
    <% @credit.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 
	<%= f.label "Team member email"%>
   
	<%= f.text_field :pending_user_email %>
  
		<%= f.label "What was team member's role?"%>
	   
		<%= f.text_field :role %>
	   
	 	
	 		<%= f.hidden_field :product_id, :value => c.product.id %>
			
			<%= f.hidden_field :current_credit_id, :value => c.id %>
			
			<%= f.hidden_field :current_credit_role, :value => c.role %>
			
		    
			<a href="/message_preview?credits_id=<%= c.id %>" target="blank">(preview the message)</a>
			
	 			<%= f.submit 'SEND REQUEST', :id => 'blue-link' %>
				
	<% end %> 
</div>
</div>
	
<script type="text/javascript">
 
$(document).ready(function(){
 
        $(".slidingDiv_facebook_<%= c.id %>").hide();
        $(".show_hide_facebook_<%= c.id %>").show();
 
    $('.show_hide_facebook_<%= c.id %>').click(function(){
    $(".slidingDiv_facebook_<%= c.id %>").slideToggle();
    });
 
});
 
</script>	


<div class="slidingDiv_facebook_<%= c.id %>">	
	<div class="credit-validate-container">
	<div style="float:right;"> <a class="show_hide_facebook_<%= c.id %>">(close X)</a></div>	
	<br />
	
	<%= form_for @credit, :validate => true do |f|%>
	<% if @credit.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

	    <ul>
	    <% @credit.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
   
			<%= f.label "What was team member's role?"%>
			<%= f.text_field :role %>

			
		 		<%= f.hidden_field :product_id, :value => c.product.id %>
			
				<%= f.hidden_field :current_credit_id, :value => c.id %>
			   
		 			<%= f.submit 'Verify Your Credit', :id => 'blue-link', :name => 'facebook' %>
				
		<% end %> 
		</div>
			</div>
	
	
			<script type="text/javascript">
 
			$(document).ready(function(){
 
			        $(".slidingDiv_co_<%= c.id %>").hide();
			        $(".show_hide_co_<%= c.id %>").show();
 
			    $('.show_hide_co_<%= c.id %>').click(function(){
			    $(".slidingDiv_co_<%= c.id %>").slideToggle();
			    });
 
			});
 
			</script>	
	

	<% end %>
<% end %>
<% end %>

app/views/credits/batch.html.erb
<div class="container_12 pages">
	<h1>Credits - Quick Add</h1>
	 <p>Use the form below to quickly add multiple credits. Previous role suggestions appear.</p>
<%= form_for(@credit) do |f| %>
 
 <%= text_field_tag :role, params[:role], data: {autocomplete_source: Credit.where(:user_id => current_user.id).order(:role).map(&:role).uniq}, :placeholder => "Type in a role", :class => "role" %> 
 

<%= select_tag :product_id, options_from_collection_for_select(Product.all, :id, :title, params[:product_id]), :class => "select-advanced" %>

    <%= f.submit 'Create Credit >', :class => 'batch'%>

<% end %>

</div>

app/views/credits/edit.html.erb
<div class="container_12 edit-credit">
	

<h1>Editing Credit</h1>

<%= render 'form' %>
<div class="back" style="margin-top:30px">
<%= link_to 'Back', :back, :class => "blue-btn" %>
</div>

</div>

app/views/credits/index.html.erb
<div class="search_header">
  <div class="container_12">
    <h1 class="grid_12">
      <%= @page_title || "Credits listing" %>
    </h1>
  </div>
</div>

<div class="container_12">
  <div class="search_results grid_12">
    <%= render "credits_list", credits: @credits %>
  </div>

  <% if @credits.respond_to? :current_page %>
    <%= paginate @credits %>
  <% end %>
</div>

app/views/credits/role.html.erb
<div class="container_12 edit-credit">

<h1>Editing Credit Role</h1>
	<h3 style="color:red;">Warning - changes to your Role or Role Description will need re-validation.</h3>
<%= render 'form' %>

</div>
</div>

app/views/credits/show.html.erb
<div class="container_12 credits-form">
	<h2>Your new credit:</h2>
<ul>
	
	<li class="<%= cycle('even', 'odd') -%>">
	<h2><% if @credit.product.image? %>
			<%= image_tag @credit.product.image.thumb.to_s %>
				 <%else%> 
			<%= image_tag '/assets/default-credit-small.jpg'%>
	 <%end%>  
	   
	 
	  <%= @credit.role%> <%= link_to "(edit)", role_credits_path(:id => @credit) %>   on   <%= link_to @credit.product.title, product_path(@credit.product)%></h2>
		
		
		
	

<br /><br /><br /><br />
	   
	
<div class="container_12">
	<p>Would you like to?</p>
	<%= link_to 'Accept this credit', product_path(@credit.product), :class => "blue-btn" %>


<%= link_to 'Decline this credit', @credit, method: :delete, data: { confirm: 'Are you sure?' }, :class => "blue-btn" %>

</div>


	</li>
			
</ul>
</div>